// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBmelibjAl-021rFjpyt619Im1PfM2f0',
    appId: '1:634660058298:web:762f502a0382e2932f7e83',
    messagingSenderId: '634660058298',
    projectId: 'lina-s-alarm',
    authDomain: 'lina-s-alarm.firebaseapp.com',
    storageBucket: 'lina-s-alarm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCdyMpF9W6e3jhJ5eB4tZvrgp6IUXEkM',
    appId: '1:634660058298:android:d6ef684b7cc863872f7e83',
    messagingSenderId: '634660058298',
    projectId: 'lina-s-alarm',
    storageBucket: 'lina-s-alarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMO87uZIURkaUrRKjT5XNEKQWnOz1nWlQ',
    appId: '1:634660058298:ios:363bd5de9e5e43a02f7e83',
    messagingSenderId: '634660058298',
    projectId: 'lina-s-alarm',
    storageBucket: 'lina-s-alarm.firebasestorage.app',
    iosBundleId: 'com.example.linasAlarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMO87uZIURkaUrRKjT5XNEKQWnOz1nWlQ',
    appId: '1:634660058298:ios:363bd5de9e5e43a02f7e83',
    messagingSenderId: '634660058298',
    projectId: 'lina-s-alarm',
    storageBucket: 'lina-s-alarm.firebasestorage.app',
    iosBundleId: 'com.example.linasAlarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBmelibjAl-021rFjpyt619Im1PfM2f0',
    appId: '1:634660058298:web:b922db017c5ef5a82f7e83',
    messagingSenderId: '634660058298',
    projectId: 'lina-s-alarm',
    authDomain: 'lina-s-alarm.firebaseapp.com',
    storageBucket: 'lina-s-alarm.firebasestorage.app',
  );
}
